name: cerl-environment
channels:
  - conda-forge
dependencies:
  - python 3.8
  - cartopy
  - pip
  - pip:
    - appnope==0.1.2; sys_platform == "darwin" or platform_system == "Darwin" or python_version >= "3.3" and sys_platform == "darwin"
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - backcall==0.2.0
    - bibliometa==0.1.3
    - bibliometa-vis==0.1.1
    - bleach==4.1.0
    - branca==0.4.2
    - cartopy==0.20.0
    - cerl==0.0.5
    - certifi==2021.5.30
    - cffi==1.14.6
    - charset-normalizer==2.0.6; python_version >= "3"
    - click==8.0.1
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colorama==0.4.4; python_version >= "3.3" and sys_platform == "win32" or sys_platform == "win32" or platform_system == "Windows"
    - cycler==0.10.0
    - cython==0.29.24
    - debugpy==1.4.3
    - decorator==5.1.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - fiona==1.8.20
    - folium==0.12.1
    - geopandas==0.9.0
    - idna==3.2; python_version >= "3"
    - ipykernel==6.4.1
    - ipython==7.27.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.0.3
    - jupyter-console==6.4.0
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2; python_version >= "3.6"
    - kiwisolver==1.3.2
    - loguru==0.5.3
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - munch==2.5.0
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.6.3
    - notebook==6.4.4
    - numpy==1.21.2
    - osmnx==1.1.1
    - packaging==21.0
    - pandas==1.3.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0; python_version >= "3.3" and sys_platform != "win32" or sys_platform != "win32"
    - pickleshare==0.7.5
    - pillow==8.3.2
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - ptyprocess==0.7.0; sys_platform != "win32" or os_name != "nt" or python_version >= "3.3" and sys_platform != "win32"
    - py==1.10.0; implementation_name == "pypy"
    - pycparser==2.20
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyproj==3.2.1
    - pyrsistent==0.18.0
    - pyshp==2.1.3
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywin32==301; sys_platform == "win32" and platform_python_implementation != "PyPy"
    - pywinpty==1.1.4; os_name == "nt"
    - pyzmq==22.3.0
    - qtconsole==5.1.1
    - qtpy==1.11.1
    - requests==2.26.0
    - rtree==0.9.7
    - scipy==1.7.1
    - send2trash==1.8.0
    - shapely==1.7.1
    - six==1.16.0
    - terminado==0.12.1
    - testpath==0.5.0
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.0
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - win32-setctime==1.0.3; sys_platform == "win32"